name: Semgrep Scan

on:
  push:
    branches:
      - main   
    paths:
      - '**/*'  

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Semgrep
      run: |
        docker run --rm \
        -v "${{ github.workspace }}/project:/src" \
        -v "${{ github.workspace }}/project/informes/segrem:/reports" \
        returntocorp/semgrep \
        semgrep --config "p/php" /src/app/ --sarif --output /reports/reporte.sarif

    - name: Commit and push SARIF report to GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add project/informes/segrem/reporte.sarif
        git commit -m "Add Semgrep report"
        git push
