name: Semgrep Scan

on:
  push:
    branches:
      - main   # Se activa cuando se hace un push a la rama 'main'
    paths:
      - '**/*'  # Se activa cuando se modifican archivos dentro del repositorio

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest  # Ejecutar en un entorno Ubuntu

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2  # Este paso descarga el código de tu repositorio

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # Prepara Docker para ejecutar el contenedor

    - name: Run Semgrep
      run: |
        docker run --rm \
        -v "${{ github.workspace }}/project:/src" \
        -v "${{ github.workspace }}/project/informes/segrem:/reports" \
        returntocorp/semgrep \
        semgrep --config "p/php" /src/app \
        --sarif --output /reports/reporte.sarif \
        --html --output /reports/reporte.html  # Genera ambos reportes SARIF y HTML

    - name: Commit and push SARIF and HTML reports to GitHub
      run: |
        git config --global user.name "github-actions"  # Configura el nombre del usuario para el commit
        git config --global user.email "github-actions@github.com"  # Configura el email del usuario
        git add project/informes/segrem/reporte.sarif  # Añade el archivo SARIF generado
        git add project/informes/segrem/reporte.html  # Añade el archivo HTML generado
        git commit -m "Add Semgrep reports (SARIF and HTML)"  # Realiza el commit
        git push  # Realiza un push para subir los reportes al repositorio
