name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    # Clona el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # PHP 8.2 según tu solicitud
        extensions: xdebug # Necesario para la cobertura de código

    # Instala las dependencias de Composer
    - name: Install dependencies
      run: |
        cd project
        composer install

    # Ejecuta PHPUnit y genera el informe HTML de cobertura
    - name: Run PHPUnit tests
      run: |
        cd project
        vendor/bin/phpunit --coverage-html coverage/html-report

    # Crea la carpeta destino si no existe y mueve el informe
    - name: Move coverage report to the target folder
      run: |
        cd project
        mkdir -p ../proyecto-si784-2024-ii-u2-ayma_tapia_poma/project/informes/pruebasunitarias
        cp -r coverage/html-report/* ../proyecto-si784-2024-ii-u2-ayma_tapia_poma/project/informes/pruebasunitarias/
    
    # (Opcional) Sube el informe como artefacto para descargarlo desde GitHub
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: phpunit-coverage-report
        path: proyecto-si784-2024-ii-u2-ayma_tapia_poma/project/informes/pruebasunitarias/
